app:
  name: short-video-core-service
  version: 0.0.1-test
  node: 2
  trace_endpoint: http://localhost:14268/api/traces # jaeger endpoint
#  trace_endpoint: http://localhost:4317

server:
  grpc:
    addr: 0.0.0.0:8001

components:
  mysql:
    default:
      host: localhost
      port: 3306
      db_name: doutok
      user: root
      password: a12bCd3_W45pUq6
  redis:
    default:
      dsn: localhost:6379
      password: root
  consul:
    default:
      address: localhost:8500

auth:
  jwt:
    access_expire: 720 # 30 days
    access_secret: "secret-key"
